name: CI

on:
  push:
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: gd, mbstring, sqlite3
