name: GitHub Actions Test
on:
  push:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installation de Composer
        uses: php-actions/composer@v6

      - name: Installation des dépendances
        uses: php-actions/phpunit@v3
        with:
          php_extensions: gd mbstring sqlite3 simplexml xdebug
          configuration: ./phpunit.xml