name: CI
on:
  push:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installation de Composer
        uses: php-actions/composer@v6

      - name: Lancement des tests PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: gd mbstring sqlite3 simplexml xdebug
          configuration: ./phpunit.xml
          bootstrap: ./tst/Bootstrap.php
          version: 9
          php_version: '8.1'

      - name: Installation de CodeCoverageSummary
        run: composer global require irongut/code-coverage-summary

      - name: Génération du rapport de couverture de code
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml
          ~/.composer/vendor/bin/code-coverage-summary clover coverage.xml