name: CI

on: 
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: Run PHPUnit 
      uses: php-actions/phpunit@v3
