name: CI

on:
  push:
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lancement de PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: gd sqlite3 dom json libxml mbstring tokenizer xml xmlwriter zip xdebug
          version: 9.6.11
          configuration: phpunit.xml

      - name: Creation du rapport de couverture de code
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: log/cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Exportation du rapport de couverture de code
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
